name: tools_common
description: common classes and utilities for oobium tools
version: 0.1.0
repository: https://github.com/jeremy-dowdall/oobium
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pubspec_parse: ^1.0.0
  yaml: ^3.1.0
  xstring: ^1.2.0

dev_dependencies:
  test: ^1.17.5
