name: xstring
description: String extensions to make working with String? variables more convenient.
version: 1.0.2
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
