name: cli_example
description: example project
version: 0.1.0
repository: https://github.com/jeremy-dowdall/oobium
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  oobium_server:
    path: ../../../server
