name: oobium_datastore
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  objectid: ^2.0.0
  stream_channel: ^2.1.0
  xstring: ^1.1.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.15.3
