name: oobium_datastore
description: Persistent DataStore for Dart applications.
version: 1.0.0-dev.1
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  objectid: ^2.0.0
  stream_channel: ^2.1.0
  xstring: ^1.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.15.3
