name: oobium
description: Framework for Clients and Servers.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.1
  objectid: ^1.1.1
  http_parser: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  mockito: ^4.1.3
  stream_channel: ^2.0.0
