name: oobium
description: Framework for Clients and Servers.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.3
  oobium_datastore:
    path: ../datastore
  oobium_websocket:
    path: ../websocket
  http_parser: ^4.0.0
  stream_channel: ^2.1.0
  xstring: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  build_runner: 2.0.4
  oobium_datastore_gen:
    path: ../datastore/gen
