name: string_x
description: String extensions to make working with String? variables more convenient.
  Useful for dealing with empty and nullable strings (isBlank, orElse, etc), code generation (camelCase, underscored, etc) or general output of data (titleize, initials, etc)
version: 1.0.0
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
