name: oobium_routing_gen
description: Generators for Oobium Routing, enabling compile-time safe routes
version: 1.0.0-dev.5
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.2
  dart_style: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.0.4
