name: oobium_host
description: Host for Oobium based projects
version: 0.1.0
repository: https://github.com/jeremy-dowdall/oobium
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  oobium_server:
    path: ../../server
  oobium_websocket:
    path: ../../websocket
  xstring: ^1.2.0

dev_dependencies:
  test: ^1.17.5
