name: tools_host
description: Host for Oobium based projects
version: 0.1.0
repository: https://github.com/jeremy-dowdall/oobium
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  oobium_server:
    path: ../../server
  oobium_websocket:
    path: ../../websocket
  pubspec_parse: ^1.0.0
  tar: ^0.4.0
  tools_common:
    path: ../common
  yaml: ^3.1.0
  xstring: ^1.2.0

dev_dependencies:
  test: ^1.17.5
