name: oobium_client
description: A simple client persistence framework.
version: 0.0.1
author:
#homepage:

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oobium:
    path: ../oobium
  provider: ^4.3.2
  path_provider: ^1.6.11
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
