name: oobium_common
description: Common classes and utilities for Oobium Clients and Servers.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.3
  mime: ^0.9.7
  http: ^0.12.2
  corsac_jwt: ^0.2.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  mockito: ^4.1.3
