name: oobium_routing
description: Simplified routing for Navigator 2.0.
  Type-safe, semi-declarative, supporting bidirectional browser address bar and nested routers.
version: 1.0.0-dev.5
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.3

flutter:
  uses-material-design: true