name: oobium_server
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  oobium:
    path: ../oobium
  meta: ^1.3.0
  http: ^0.13.1
  objectid: ^1.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  mockito: ^5.0.2
  stream_channel: ^2.1.0
