name: oobium_server
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  oobium:
    path: ../oobium
  meta: ^1.2.3
  http: ^0.12.2
  objectid: ^1.1.1

dev_dependencies:
  oobium_test:
    path: ../oobium_test
  pedantic: ^1.9.0
  test: ^1.15.3
  mockito: ^4.1.3
  stream_channel: ^2.0.0
