name: json
description: JSON conversion helpers and extensions.
version: 0.0.1
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
