name: example
description: Websocket Example
version: 1.0.0
repository: https://github.com/jeremy-dowdall/oobium

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  oobium_server:
    # When depending on this package from a real application you should use:
    #   oobium_server: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../server
  oobium_websocket:
    # When depending on this package from a real application you should use:
    #   oobium_websocket: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
