name: oobium_flutter
description: A simple client persistence framework.
version: 0.0.1
author:
#homepage:

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oobium:
    path: ../oobium
  oobium_routing:
    path: ../oobium_routing
  connectivity: ^2.0.2
  provider: ^4.3.2
  path_provider: ^1.6.11

dev_dependencies:
  oobium_test:
    path: ../../oobium/oobium_test
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
  stream_channel: ^2.0.0
