name: oobium_client_gen
description: A simple persistence framework.
version: 0.0.1
author:
#homepage:

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  oobium:
    path: ../oobium

dev_dependencies:
  oobium_test:
    path: ../oobium_test
  test: ^1.15.3
  mockito: ^4.1.2
