name: oobium_datastore_gen
description: Generators for Oobium Datastore, enabling custom schema development
version: 1.0.0-dev.1
repository: https://github.com/jeremy-dowdall/oobium

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.2
  collection: ^1.15.0
  dart_style: ^2.0.1
  xstring: ^1.2.0

dev_dependencies:
  test: ^1.15.3
  build_runner: ^2.0.4
  oobium_datastore:
    path: ../datastore
