name: firebase_auth_validator
description: An AuthValidator for Firebase Users.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  oobium_server:
    path: ../oobium_server
  corsac_jwt: ^0.4.0
  meta: ^1.3.0
  http: ^0.13.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  mockito: ^4.1.3
