name: tools_bootstrap
description: Bootstrap server for Oobium based projects
version: 0.1.0
repository: https://github.com/jeremy-dowdall/oobium
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  tar: ^0.4.0
