name: Tools Host Build

on:
  push
#  push:
#    paths:
#      - 'tools/host/lib/boot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - run: mkdir -p dist

      - run: dart pub get
        working-directory: tools/host

      - run: dart compile exe tools/host/lib/boot/main.dart -o dist/boot-linux.exe

      - run: echo -e ${{ secrets.DEPLOY_SSH_KEY }} > _
      - run: 'scp dist/boot-linux.exe root@oobium.download:/files/boot-linux.exe'
