name: Tools Host Build

on:
  push:
    paths:
      - 'tools/host/lib/boot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - run: mkdir -p dist
      - run: dart compile exe tools/host/lib/boot/main.dart -o dist/boot-linux.exe

      - uses: actions/upload-artifact@v2
        with:
          name: boot-linux.exe
          path: dist/boot-linux.exe
